#!/usr/bin/env node
/**
 * The Content-Security-Policy, generated from the page it protects (D10).
 *
 *   node scripts/csp.mjs           # write nginx/csp.conf
 *   node scripts/csp.mjs --check   # exit 1 if nginx/csp.conf is not what the page needs
 *
 * The policy allows the page's one inline script and one inline style block by
 * their SHA-256, so it has to change whenever either of them does. Generated
 * rather than hand-edited, and checked in CI before an image is built, so a copy
 * edit can never ship a page that its own header blocks.
 *
 * It also refuses the things a same-origin policy would silently break rather
 * than report here: an external script, an inline event handler, a
 * `javascript:` URL. Each would reach the browser, be blocked there, and show
 * up as a dead button instead of a failed build.
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PAGE = path.join(ROOT, "site", "index.html");
const OUT = path.join(ROOT, "nginx", "csp.conf");

/** What a browser hashes: the element's text, exactly, as UTF-8. */
const sha256 = (text) => `'sha256-${createHash("sha256").update(text, "utf8").digest("base64")}'`;

export function inlineBlocks(html) {
  const scripts = [...html.matchAll(/<script(\s[^>]*)?>([\s\S]*?)<\/script\s*>/gi)];
  const styles = [...html.matchAll(/<style(\s[^>]*)?>([\s\S]*?)<\/style\s*>/gi)];
  return {
    scripts: scripts.map((m) => ({ attributes: m[1] ?? "", text: m[2] })),
    styles: styles.map((m) => ({ attributes: m[1] ?? "", text: m[2] })),
  };
}

/** Everything a same-origin policy would block without a word at build time. */
export function problems(html) {
  const found = [];
  const { scripts } = inlineBlocks(html);
  for (const { attributes } of scripts) {
    if (/\ssrc\s*=/i.test(attributes)) found.push(`a <script${attributes}> loads a file; this policy allows inline scripts by hash only`);
  }
  /* Tags only, with script and style contents taken out first. */
  const markup = html.replace(/<(script|style)(\s[^>]*)?>[\s\S]*?<\/\1\s*>/gi, "");
  for (const tag of markup.match(/<[a-z][^>]*>/gi) ?? []) {
    const handler = tag.match(/\s(on[a-z]+)\s*=/i);
    if (handler) found.push(`inline event handler ${handler[1]} in ${tag.slice(0, 60)}`);
    if (/=\s*["']?\s*javascript:/i.test(tag)) found.push(`javascript: URL in ${tag.slice(0, 60)}`);
  }
  return found;
}

export function policy(html) {
  const { scripts, styles } = inlineBlocks(html);
  return [
    // Nothing is allowed unless a line below allows it.
    ["default-src", "'none'"],
    // The one inline script, by hash. No 'unsafe-inline', no file, no eval.
    ["script-src", ...scripts.map((s) => sha256(s.text))],
    // Styles, in two parts (D10). The <style> element by hash, and style=""
    // attributes allowed: the page has 26 of them, each setting a CSS custom
    // property such as --i:3, and an attribute cannot run code.
    ["style-src-elem", ...styles.map((s) => sha256(s.text))],
    ["style-src-attr", "'unsafe-inline'"],
    // For browsers from before style-src-elem and -attr (Safari < 15.4,
    // Firefox < 108), which read only this line and would otherwise refuse the
    // attributes. Browsers that know the two lines above ignore it for styles.
    ["style-src", "'unsafe-inline'"],
    // The five woff2 files next to the page.
    ["font-src", "'self'"],
    // One image, and it is inline: the check mark is an SVG data URI in the CSS.
    ["img-src", "data:"],
    // The waitlist form is a mockup whose script prevents sending; should the
    // script ever not run, it may only go back to this origin.
    ["form-action", "'self'"],
    ["base-uri", "'none'"],
    ["frame-ancestors", "'none'"],
  ];
}

export function render(html) {
  const value = policy(html)
    .map((directive) => directive.join(" "))
    .join("; ");
  return [
    "# GENERATED by scripts/csp.mjs from site/index.html. Do not edit: run",
    "# `node scripts/csp.mjs` after changing the page, and commit both (D10).",
    `add_header Content-Security-Policy "${value}" always;`,
    "",
  ].join("\n");
}

const invokedDirectly =
  process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  const html = readFileSync(PAGE, "utf8");
  const found = problems(html);
  if (found.length > 0) {
    for (const problem of found) process.stderr.write(`csp: ${problem}\n`);
    process.exit(1);
  }

  const wanted = render(html);
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(OUT, "utf8").replace(/\r\n/g, "\n");
    } catch {
      /* missing is the same as wrong */
    }
    if (current !== wanted) {
      process.stderr.write(
        "csp: nginx/csp.conf does not match site/index.html.\n" +
          "     The page's inline script or style changed and the policy did not.\n" +
          "     Run `node scripts/csp.mjs` and commit nginx/csp.conf.\n",
      );
      process.exit(1);
    }
    process.stdout.write("csp: nginx/csp.conf matches site/index.html\n");
  } else {
    writeFileSync(OUT, wanted);
    const { scripts, styles } = inlineBlocks(html);
    process.stdout.write(`csp: wrote nginx/csp.conf (${scripts.length} script, ${styles.length} style hashed)\n`);
  }
}
